// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weyllamkalycvywcurid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleWxsYW1rYWx5Y3Z5d2N1cmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDIxNjQsImV4cCI6MjA2NzcxODE2NH0.b7hE85ttOjdBsWyO03Cuvf32VuV81NClg8pfj8tR-tU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});